version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - "3306:3306" # Host:Container port mapping
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: eventsProject
    volumes:
      - db:/var/lib/mysql
    networks:
      - backendNetwork  # Attach to the custom network

  eventsProject-backend:
    image: mohamedmehdimsolli/eventsproject:v1.0-prod
    restart: unless-stopped
    ports:
      - "8089:8089" # Host:Container port mapping
    depends_on:
      - mysqldb
    networks:
      - backendNetwork  # Attach to the custom network

networks:
  backendNetwork:  # Define a custom network
    driver: bridge

volumes:
  db: # Volume for mysqldb
